serviceName: api_gateway_service
jwt:
  secretKey: your-simple-secret-key
grpc:
  user_service: :5009
http:
  port: :5001
  development: true
  basePath: /api/v1
  productPath: /api/v1/products
  userPath: /auth
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: json
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
jaeger:
  enable: true
  serviceName: api_gateway_service
  hostPort: "localhost:6831"
  logSpans: false
kafka:
  brokers: [ "localhost:9092" ]
  groupID: user_microservice_consumer
  initTopics: true
kafkaTopics:
  userCreate:
    topicName: user_create
    partitions: 10
    replicationFactor: 1
  userUpdate:
    topicName: user_update
    partitions: 10
    replicationFactor: 1
  userCreated:
    topicName: user_created
    partitions: 10
    replicationFactor: 1
  userUpdated:
    topicName: user_updated
    partitions: 10
    replicationFactor: 1
  userDeleted:
    topicName: user_deleted
    partitions: 10
    replicationFactor: 1  