serviceName: api_gateway_service
jwt:
  secretKey: your-simple-secret-key
grpc:
  user_service: :5009
http:
  port: :5001
  development: true
  basePath: /api/v1
  productPath: /api/v1/products
  userPath: /auth
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: json
kafka:
  brokers: [ "localhost:9002" ]
  groupId: api_gateway_consumer
  initTopics: true
kafkaTopics:
  productCreate:
    topicName: product_create
    partitions: 10
    replicationFactor: 1
  productUpdate:
    topicName: product_update
    partitions: 10
    replicationFactor: 1
  productDelete:
    topicName: product_delete
    partitions: 10
    replicationFactor: 1
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
jaeger:
  enable: true
  serviceName: api_gateway_service
  hostPort: "localhost:6831"
  logSpans: false