definitions:
  dto.PhoneVerificationRes:
    properties:
      verification_key:
        type: string
    type: object
  dto.User:
    properties:
      email:
        type: string
      id:
        type: string
      phone:
        type: string
      user_id:
        type: string
    type: object
  dto.UserCreateRes:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_type:
        type: integer
    type: object
info:
  contact: {}
  description: hey there
  title: Tag Service Api
paths:
  /auth:
    get:
      consumes:
      - application/json
      description: Get User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.User'
      summary: Get User
      tags:
      - Get User v1
    post:
      consumes:
      - application/json
      description: Update User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.User'
      summary: Update User
      tags:
      - Update User v1
  /auth/login:
    post:
      consumes:
      - application/json
      description: Phone needed verificationKey && SMS
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserCreateRes'
      summary: loginUser
      tags:
      - LoginPhone v1
  /auth/verification:
    post:
      consumes:
      - application/json
      description: Phone send
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PhoneVerificationRes'
      summary: verification for Phone
      tags:
      - VerificationKey v1
swagger: "2.0"
