definitions:
  dto.PhoneVerificationReq:
    properties:
      phone:
        type: string
    type: object
  dto.PhoneVerificationRes:
    properties:
      verification_key:
        type: string
    type: object
  dto.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      phone:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  dto.UserCreateReq:
    properties:
      sms:
        type: string
      verification_key:
        type: string
    type: object
  dto.UserCreateRes:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_type:
        type: integer
    type: object
  dto.UserUpdateReq:
    properties:
      email:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
      userId:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth:
    get:
      consumes:
      - application/json
      description: Get User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.User'
      summary: Get User
      tags:
      - Auth
    post:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: Update User Request
        in: body
        name: user_update
        required: true
        schema:
          $ref: '#/definitions/dto.UserUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.User'
      summary: Update User
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Phone needed verificationKey && SMS
      parameters:
      - description: Verification Key And SMS Request
        in: body
        name: verificationKey
        required: true
        schema:
          $ref: '#/definitions/dto.UserCreateReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserCreateRes'
      summary: loginUser
      tags:
      - Auth
  /auth/verification:
    post:
      consumes:
      - application/json
      description: Phone send
      parameters:
      - description: Phone Verification Request
        in: body
        name: phone_verification
        required: true
        schema:
          $ref: '#/definitions/dto.PhoneVerificationReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PhoneVerificationRes'
      summary: verification for Phone
      tags:
      - Auth
swagger: "2.0"
